"""Language trainer -- async parallel quantum training for multilingual knowledge.

Runs alongside the ContinuousTrainer, ingesting open-source parallel corpora
into the LQNN quantum memory. Each sentence pair is CLIP-encoded and stored
in ChromaDB with bilingual associations generated by the LLM.

Training pipeline per language:
1. Download dataset (async HTTP)
2. Parse sentence pairs
3. Parallel CLIP encoding (ThreadPoolExecutor)
4. Store in VectorStore with language metadata
5. Background LLM association generation (grammar, cognates, cultural context)
6. Progress tracking per language
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from lqnn.core.associative_memory import AssociativeMemory
from lqnn.core.vector_store import VectorEntry
from lqnn.training.dataset_registry import DatasetRegistry, SentencePair

log = logging.getLogger(__name__)

STATE_FILE = Path("data/state/language_state.json")

SUPPORTED_LANGUAGES = {
    "ja": "Japanese",
    "ru": "Russian",
    "it": "Italian",
    "zh": "Chinese",
    "ko": "Korean",
    "fr": "French",
    "de": "German",
    "es": "Spanish",
    "pt": "Portuguese",
    "ar": "Arabic",
}

BATCH_SIZE = 20
MAX_PAIRS_PER_CYCLE = 200
CYCLE_SLEEP_S = 30


@dataclass
class LanguageProgress:
    lang_code: str
    lang_name: str
    pairs_stored: int = 0
    concepts: int = 0
    associations: int = 0
    datasets_downloaded: int = 0
    total_pairs: int = 0
    status: str = "idle"
    last_dataset: str = ""
    last_update: float = field(default_factory=time.time)


class LanguageTrainer:
    """Async language training engine with parallel quantum encoding.

    Coexists with ContinuousTrainer -- both write to the same ChromaDB
    vector store, enriching the quantum brain with multilingual knowledge.
    """

    def __init__(self, memory: AssociativeMemory) -> None:
        self.memory = memory
        self.registry = DatasetRegistry()
        self._running = False
        self._tasks: dict[str, asyncio.Task] = {}
        self._progress: dict[str, LanguageProgress] = {}
        self._event_callback = None
        self._executor = ThreadPoolExecutor(max_workers=3)
        self._log: list[dict] = []
        self._load_state()

    def set_event_callback(self, callback) -> None:
        self._event_callback = callback

    def _emit(self, event_type: str, data: dict) -> None:
        entry = {
            "type": event_type,
            "timestamp": time.time(),
            **data,
        }
        self._log.append(entry)
        if len(self._log) > 500:
            self._log = self._log[-250:]
        if self._event_callback:
            try:
                self._event_callback(entry)
            except Exception:
                pass

    @property
    def training_log(self) -> list[dict]:
        return self._log

    def _save_state(self) -> None:
        try:
            STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
            state = {}
            for code, prog in self._progress.items():
                state[code] = {
                    "pairs_stored": prog.pairs_stored,
                    "concepts": prog.concepts,
                    "associations": prog.associations,
                    "datasets_downloaded": prog.datasets_downloaded,
                    "total_pairs": prog.total_pairs,
                    "last_dataset": prog.last_dataset,
                    "last_update": prog.last_update,
                }
            with open(STATE_FILE, "w") as f:
                json.dump(state, f)
        except Exception as e:
            log.debug("Failed to save language state: %s", e)

    def _load_state(self) -> None:
        try:
            if STATE_FILE.exists():
                with open(STATE_FILE, "r") as f:
                    state = json.load(f)
                for code, data in state.items():
                    self._progress[code] = LanguageProgress(
                        lang_code=code,
                        lang_name=SUPPORTED_LANGUAGES.get(code, code),
                        pairs_stored=data.get("pairs_stored", 0),
                        concepts=data.get("concepts", 0),
                        associations=data.get("associations", 0),
                        datasets_downloaded=data.get("datasets_downloaded", 0),
                        total_pairs=data.get("total_pairs", 0),
                        last_dataset=data.get("last_dataset", ""),
                        last_update=data.get("last_update", 0),
                    )
                log.info("Restored language state for %d languages", len(self._progress))
        except Exception as e:
            log.debug("Failed to load language state: %s", e)

    def _get_progress(self, lang_code: str) -> LanguageProgress:
        if lang_code not in self._progress:
            self._progress[lang_code] = LanguageProgress(
                lang_code=lang_code,
                lang_name=SUPPORTED_LANGUAGES.get(lang_code, lang_code),
            )
        return self._progress[lang_code]

    async def start(self, languages: list[str] | None = None) -> None:
        """Start training for specified languages (or all if None)."""
        langs = languages or list(SUPPORTED_LANGUAGES.keys())
        self._running = True

        for lang in langs:
            if lang not in SUPPORTED_LANGUAGES:
                log.warning("Unsupported language: %s", lang)
                continue
            if lang in self._tasks and not self._tasks[lang].done():
                continue

            prog = self._get_progress(lang)
            prog.status = "training"
            task = asyncio.create_task(self._train_language(lang))
            self._tasks[lang] = task

        self._emit("lang_train_start", {
            "message": f"Language training started for {', '.join(langs)}",
            "languages": langs,
        })

    async def stop(self, languages: list[str] | None = None) -> None:
        """Stop training for specified languages (or all)."""
        langs = languages or list(self._tasks.keys())

        for lang in langs:
            if lang in self._tasks and not self._tasks[lang].done():
                self._tasks[lang].cancel()
                try:
                    await self._tasks[lang]
                except asyncio.CancelledError:
                    pass
            prog = self._get_progress(lang)
            prog.status = "idle"

        if not languages:
            self._running = False

        self._emit("lang_train_stop", {
            "message": f"Language training stopped for {', '.join(langs)}",
            "languages": langs,
        })
        self._save_state()

    async def _train_language(self, lang_code: str) -> None:
        """Main training loop for a single language.

        Cycles through available datasets, downloading and ingesting pairs.
        """
        prog = self._get_progress(lang_code)
        lang_name = SUPPORTED_LANGUAGES.get(lang_code, lang_code)

        self._emit("lang_train_cycle", {
            "lang_code": lang_code,
            "message": f"Starting training loop for {lang_name}",
        })

        while self._running:
            try:
                for ds in self.registry.available_datasets():
                    if not self._running:
                        break
                    if lang_code not in ds.supported_langs:
                        continue

                    await self._download_and_ingest(ds.id, lang_code, prog)

            except asyncio.CancelledError:
                raise
            except Exception as exc:
                log.error("Language training error for %s: %s", lang_code, exc)
                self._emit("lang_error", {
                    "lang_code": lang_code,
                    "message": f"Error training {lang_name}: {exc}",
                })

            prog.status = "idle" if not self._running else "training"
            self._save_state()

            if self._running:
                await asyncio.sleep(CYCLE_SLEEP_S)

        prog.status = "idle"
        self._save_state()

    async def _download_and_ingest(
        self,
        dataset_id: str,
        lang_code: str,
        prog: LanguageProgress,
    ) -> None:
        """Download dataset (if needed) and ingest pairs into quantum memory."""
        lang_name = SUPPORTED_LANGUAGES.get(lang_code, lang_code)

        if not self.registry.is_downloaded(dataset_id, lang_code):
            prog.status = "downloading"
            self._emit("lang_dataset_downloading", {
                "lang_code": lang_code,
                "dataset": dataset_id,
                "message": f"Downloading {dataset_id} for {lang_name}...",
            })

            def _progress_cb(info: dict) -> None:
                self._emit("lang_download_progress", {
                    "lang_code": lang_code,
                    "dataset": dataset_id,
                    **info,
                })

            try:
                await self.registry.download_dataset(
                    dataset_id, lang_code, progress_callback=_progress_cb,
                )
                prog.datasets_downloaded += 1
                self._emit("lang_dataset_downloaded", {
                    "lang_code": lang_code,
                    "dataset": dataset_id,
                    "message": f"Downloaded {dataset_id} for {lang_name}",
                })
            except Exception as exc:
                self._emit("lang_error", {
                    "lang_code": lang_code,
                    "dataset": dataset_id,
                    "message": f"Download failed: {exc}",
                })
                return

        prog.status = "training"
        prog.last_dataset = dataset_id

        pairs_batch: list[SentencePair] = []
        processed = 0

        parser = self.registry.parse_pairs(
            dataset_id, lang_code, max_pairs=MAX_PAIRS_PER_CYCLE,
        )

        for pair in parser:
            if not self._running:
                break

            pairs_batch.append(pair)

            if len(pairs_batch) >= BATCH_SIZE:
                stored = await self._store_batch(pairs_batch, lang_code, prog)
                processed += stored
                pairs_batch = []

                if processed % 100 == 0:
                    self._emit("lang_progress", {
                        "lang_code": lang_code,
                        "dataset": dataset_id,
                        "pairs_processed": processed,
                        "total_stored": prog.pairs_stored,
                        "message": f"[{lang_code.upper()}] {processed} pairs processed from {dataset_id}",
                    })
                    self._save_state()

                await asyncio.sleep(0.05)

        if pairs_batch:
            stored = await self._store_batch(pairs_batch, lang_code, prog)
            processed += stored

        self._emit("lang_progress", {
            "lang_code": lang_code,
            "dataset": dataset_id,
            "pairs_processed": processed,
            "total_stored": prog.pairs_stored,
            "message": f"[{lang_code.upper()}] Completed {dataset_id}: {processed} pairs ingested",
        })

        prog.total_pairs = max(prog.total_pairs, prog.pairs_stored)
        self._save_state()

    async def _store_batch(
        self,
        pairs: list[SentencePair],
        lang_code: str,
        prog: LanguageProgress,
    ) -> int:
        """Encode and store a batch of sentence pairs using parallel CLIP encoding.

        Each pair is stored as a concept in the quantum memory with bilingual
        metadata and an LLM-generated linguistic association.
        """
        stored = 0
        loop = asyncio.get_event_loop()

        encode_futures = []
        for pair in pairs:
            bilingual = f"{pair.source_text} | {pair.target_text}"
            future = loop.run_in_executor(
                self._executor,
                self.memory.clip.encode_text,
                bilingual[:512],
            )
            encode_futures.append((pair, future))

        for pair, future in encode_futures:
            try:
                vector = await future

                concept_id = self._make_lang_id(pair)

                try:
                    existing = self.memory.store.get_concept(concept_id)
                    if existing:
                        continue
                except Exception:
                    pass

                bilingual_text = f"{pair.source_text} | {pair.target_text}"
                full_text = (
                    f"[{pair.source_lang.upper()}->{pair.target_lang.upper()}] "
                    f"English: {pair.source_text}\n"
                    f"{SUPPORTED_LANGUAGES.get(pair.target_lang, pair.target_lang)}: "
                    f"{pair.target_text}"
                )

                entry = VectorEntry(
                    id=concept_id,
                    vector=vector,
                    concept=bilingual_text[:200],
                    source=f"language:{pair.dataset}",
                    volatility=0.15,
                    confidence=0.85,
                    metadata={
                        "lang_code": pair.target_lang,
                        "lang_name": SUPPORTED_LANGUAGES.get(
                            pair.target_lang, pair.target_lang
                        ),
                        "source_text": pair.source_text[:500],
                        "target_text": pair.target_text[:500],
                        "dataset": pair.dataset,
                        "curation": "language_corpus",
                        "full_text": full_text[:2000],
                    },
                )
                self.memory.store.add_concept(entry)

                stored += 1
                prog.pairs_stored += 1
                prog.concepts += 1

                self._emit("lang_pair_stored", {
                    "lang_code": pair.target_lang,
                    "source_text": pair.source_text[:60],
                    "target_text": pair.target_text[:60],
                    "dataset": pair.dataset,
                })

            except Exception as exc:
                log.debug("Failed to store pair: %s", exc)
                continue

        if stored > 0:
            self._schedule_associations(pairs[:5], lang_code)

        return stored

    def _schedule_associations(
        self,
        sample_pairs: list[SentencePair],
        lang_code: str,
    ) -> None:
        """Schedule background LLM association generation for language pairs.

        Generates linguistic associations: grammar patterns, cognates, etc.
        """
        lang_name = SUPPORTED_LANGUAGES.get(lang_code, lang_code)
        assoc_queue = getattr(self.memory, "_assoc_bg_queue", None)
        if not assoc_queue:
            return

        for pair in sample_pairs:
            prompt = (
                f"Given the {lang_name} translation pair:\n"
                f'English: "{pair.source_text}"\n'
                f'{lang_name}: "{pair.target_text}"\n\n'
                f"Generate 3 brief linguistic associations (grammar patterns, "
                f"cognates, pronunciation tips, or cultural context). "
                f"Output ONLY a numbered list."
            )
            concept_id = self._make_lang_id(pair)
            try:
                assoc_queue.put_nowait((concept_id, prompt, 3))
                prog = self._get_progress(lang_code)
                prog.associations += 3
            except Exception:
                pass

    @staticmethod
    def _make_lang_id(pair: SentencePair) -> str:
        raw = f"lang:{pair.target_lang}:{pair.source_text}:{pair.target_text}"
        return hashlib.sha256(raw.encode()).hexdigest()[:24]

    async def download_dataset_manual(self, dataset_id: str) -> dict:
        """Trigger manual download of a dataset for all its supported languages."""
        ds = self.registry.get_dataset(dataset_id)
        if not ds:
            return {"error": f"Unknown dataset: {dataset_id}"}

        results = {}
        for lang in ds.supported_langs:
            if lang not in SUPPORTED_LANGUAGES:
                continue
            try:
                await self.registry.download_dataset(dataset_id, lang)
                results[lang] = "downloaded"
                self._get_progress(lang).datasets_downloaded += 1
                self._emit("lang_dataset_downloaded", {
                    "lang_code": lang,
                    "dataset": dataset_id,
                    "message": f"Downloaded {dataset_id} for {SUPPORTED_LANGUAGES[lang]}",
                })
            except Exception as exc:
                results[lang] = f"error: {exc}"
                self._emit("lang_error", {
                    "lang_code": lang,
                    "dataset": dataset_id,
                    "message": f"Download failed for {lang}: {exc}",
                })

        self._save_state()
        return {"dataset": dataset_id, "results": results}

    def status(self) -> dict[str, Any]:
        """Return per-language training status."""
        languages = {}
        for code in SUPPORTED_LANGUAGES:
            prog = self._get_progress(code)
            languages[code] = {
                "lang_name": prog.lang_name,
                "pairs_stored": prog.pairs_stored,
                "concepts": prog.concepts,
                "associations": prog.associations,
                "datasets_downloaded": prog.datasets_downloaded,
                "total_pairs": max(prog.total_pairs, prog.pairs_stored),
                "status": prog.status,
                "last_dataset": prog.last_dataset,
            }

        return {
            "running": self._running,
            "languages": languages,
            "active_tasks": sum(
                1 for t in self._tasks.values() if not t.done()
            ),
        }
